---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch: [main]

workspace:
  path: /go/src/github.com/${DRONE_REPO}

steps:
  - name: test
    image: golangci/golangci-lint:v2.4.0

    commands:
      - make test

  - name: license-check
    image: public.ecr.aws/kanopy/licensed-go:4.0.4-0.3.0
    commands:
      - licensed cache
      - licensed status
